### PR TITLE
Work around write-file-atomic Windows EPERM issue

### LINKED ISSUE #14: Implement work-around for Windows EPERM issue
From https://github.com/istanbuljs/istanbuljs/issues/141#issuecomment-490083960 the write-file-atomic bug is long standing, we need to try creating a work-around for this.  Should be possible to retry reading the file if we fail to write the cache file, assuming we failed to write because another process was already writing.  Maybe fail on the 3rd retry.

### PR DESCRIPTION
**Pull request by coreyfarrell**
Fixes #14

---

Going to wait for more feedback from @ehmicky to verify this resolves the issue before I consider merging.  Just posting the PR so it becomes visible to others in case someone objects to using a retry cycle.  My thinking is that caching-transform success implies that the cache file has been successfully created.

### CODE REVIEW

**Comment by coreyfarrell** [comment]
@ehmicky has stated that this fixes testing on Windows.  Anyone have feelings for/against this approach to fixing the issue?  @bcoe @JaKXz?

**Comment by bcoe** [comment]
@coreyfarrell this is definitely a little icky :smile: 

I'll :+1:, but is there a tracking issue on the Node.js project for this regression?

**Comment by coreyfarrell** [comment]
To my knowledge it's not a node.js regression.  See https://github.com/npm/write-file-atomic/issues/28.

File: index.js [hunk 1]
```diff
@@ -72,12 +72,29 @@ function wrap(opts) {
...
+				return fs.readFileSync(cachedPath, encoding);
+			} catch (error) {
+				if (!result) {
+					result = transform(input, metadata, hash);
+				}
+
+				try {
+					writeFileAtomic.sync(cachedPath, result, {encoding});
+					return result;
+				} catch (error) {
```
Comment (JaKXz) [inline index.js]: Forgive me if I'm wrong, but isn't this a naming collision with the error object from the previous catch block?

Comment (coreyfarrell) [reply index.js]: The variable is scoped, so `error` from the inner catch is what we throw on line 94.  This is just habit I always use `catch (error) { ... }` except when I need the outer error from an inner catch.  I can see how this could be confusing I can change the outer scope to `readError` if you want.

Comment (JaKXz) [reply index.js]: I mean the error from the previous scope is also never used so it would be nice to have the new `catch {}` syntax

Comment (coreyfarrell) [reply index.js]: As much as I'd love to eliminate node.js 8 and 10 right now ... :smile:

**Comment by coreyfarrell** [comment]
@JaKXz I'm leaving the `unbreak-windows` branch in place for now, it looks like @ehmicky is installing from that branch.

@ehmicky please point your package.json directly to 1689877d71e9cc57f3ab0448438b3c10e56057e5 (the commit merged to `master` for this PR).  At some point the `unbreak-windows` branch will be deleted.

**Comment by ehmicky** [comment]
Thanks for checking it! I've changed the reference to point to the commit hash, you can now safely remove the `unbreak-windows` branch. It's not used in production by anyone anymore.
